# Site settings
title: MarsLink-マーズリンク- 移動空間をメディアに変えるスタートアップ
email: info@marslink.co.jp
description: >-
  株式会社MarsLink（マーズリンク）は、主力サービス「CabinTime」を通じて、飛行機・船舶から宇宙船まで、すべての移動空間を"知と感動"の体験空間に変えるメディア・テックスタートアップです。
keywords: "MarsLink, CabinTime, 移動空間, デジタル変革, イノベーション, テクノロジー, 持続可能, 社会課題解決"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marslink.co.jp" # the base hostname & protocol for your site

# Social media handles
twitter_username: marslink_japan
github_username: marslink

# Build settings
markdown: kramdown
highlighter: rouge
theme: 

# Include and exclude files
include:
  - "_pages"
  - "assets"

exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - deploy.sh
  - PHP_SETUP_GUIDE.md
  - template-usage-example.md
  - base-template.html

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "MarsLink"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# SEO settings
author: MarsLink
logo: /assets/images/logo.png
social:
  name: 株式会社MarsLink
  links:
    - https://twitter.com/marslink_japan

# Analytics (設定時にコメントアウト解除)
google_analytics: G-4GB470X3SK
google_site_verification: "A7Ao6K_9KyyD2MJWgymaOyTS-hsEZyYXIKGvJO1L0nw"
# bing_site_verification: "your-bing-verification-code"

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed 